<?php

use Illuminate\Database\Seeder;

class LocationSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        $divisions = array(
            array('id' => '1','name' => 'Chattagram'),
            array('id' => '2','name' => 'Rajshahi'),
            array('id' => '3','name' => 'Khulna'),
            array('id' => '4','name' => 'Barisal'),
            array('id' => '5','name' => 'Sylhet'),
            array('id' => '6','name' => 'Dhaka'),
            array('id' => '7','name' => 'Rangpur'),
            array('id' => '8','name' => 'Mymensingh')
          );
       foreach($divisions as $division){
            \App\Division::create($division);
        }


        $districts = array(
            array('id' => '1','name' => 'Comilla','division_id' => '1'),
            array('id' => '2','name' => 'Feni','division_id' => '1'),
            array('id' => '3','name' => 'Brahmanbaria','division_id' => '1'),
            array('id' => '4','name' => 'Rangamati','division_id' => '1'),
            array('id' => '5','name' => 'Noakhali','division_id' => '1'),
            array('id' => '6','name' => 'Chandpur','division_id' => '1'),
            array('id' => '7','name' => 'Lakshmipur','division_id' => '1'),
            array('id' => '8','name' => 'Chattogram','division_id' => '1'),
            array('id' => '9','name' => 'Coxsbazar','division_id' => '1'),
            array('id' => '10','name' => 'Khagrachhari','division_id' => '1'),
            array('id' => '11','name' => 'Bandarban','division_id' => '1'),
            array('id' => '12','name' => 'Sirajganj','division_id' => '2'),
            array('id' => '13','name' => 'Pabna','division_id' => '2'),
            array('id' => '14','name' => 'Bogura','division_id' => '2'),
            array('id' => '15','name' => 'Rajshahi','division_id' => '2'),
            array('id' => '16','name' => 'Natore','division_id' => '2'),
            array('id' => '17','name' => 'Joypurhat','division_id' => '2'),
            array('id' => '18','name' => 'Chapainawabganj','division_id' => '2'),
            array('id' => '19','name' => 'Naogaon','division_id' => '2'),
            array('id' => '20','name' => 'Jashore','division_id' => '3'),
            array('id' => '21','name' => 'Satkhira','division_id' => '3'),
            array('id' => '22','name' => 'Meherpur','division_id' => '3'),
            array('id' => '23','name' => 'Narail','division_id' => '3'),
            array('id' => '24','name' => 'Chuadanga','division_id' => '3'),
            array('id' => '25','name' => 'Kushtia','division_id' => '3'),
            array('id' => '26','name' => 'Magura','division_id' => '3'),
            array('id' => '27','name' => 'Khulna','division_id' => '3'),
            array('id' => '28','name' => 'Bagerhat','division_id' => '3'),
            array('id' => '29','name' => 'Jhenaidah','division_id' => '3'),
            array('id' => '30','name' => 'Jhalakathi','division_id' => '4'),
            array('id' => '31','name' => 'Patuakhali','division_id' => '4'),
            array('id' => '32','name' => 'Pirojpur','division_id' => '4'),
            array('id' => '33','name' => 'Barisal','division_id' => '4'),
            array('id' => '34','name' => 'Bhola','division_id' => '4'),
            array('id' => '35','name' => 'Barguna','division_id' => '4'),
            array('id' => '36','name' => 'Sylhet','division_id' => '5'),
            array('id' => '37','name' => 'Moulvibazar','division_id' => '5'),
            array('id' => '38','name' => 'Habiganj','division_id' => '5'),
            array('id' => '39','name' => 'Sunamganj','division_id' => '5'),
            array('id' => '40','name' => 'Narsingdi','division_id' => '6'),
            array('id' => '41','name' => 'Gazipur','division_id' => '6'),
            array('id' => '42','name' => 'Shariatpur','division_id' => '6'),
            array('id' => '43','name' => 'Narayanganj','division_id' => '6'),
            array('id' => '44','name' => 'Tangail','division_id' => '6'),
            array('id' => '45','name' => 'Kishoreganj','division_id' => '6'),
            array('id' => '46','name' => 'Manikganj','division_id' => '6'),
            array('id' => '47','name' => 'Dhaka','division_id' => '6'),
            array('id' => '48','name' => 'Munshiganj','division_id' => '6'),
            array('id' => '49','name' => 'Rajbari','division_id' => '6'),
            array('id' => '50','name' => 'Madaripur','division_id' => '6'),
            array('id' => '51','name' => 'Gopalganj','division_id' => '6'),
            array('id' => '52','name' => 'Faridpur','division_id' => '6'),
            array('id' => '53','name' => 'Panchagarh','division_id' => '7'),
            array('id' => '54','name' => 'Dinajpur','division_id' => '7'),
            array('id' => '55','name' => 'Lalmonirhat','division_id' => '7'),
            array('id' => '56','name' => 'Nilphamari','division_id' => '7'),
            array('id' => '57','name' => 'Gaibandha','division_id' => '7'),
            array('id' => '58','name' => 'Thakurgaon','division_id' => '7'),
            array('id' => '59','name' => 'Rangpur','division_id' => '7'),
            array('id' => '60','name' => 'Kurigram','division_id' => '7'),
            array('id' => '61','name' => 'Sherpur','division_id' => '8'),
            array('id' => '62','name' => 'Mymensingh','division_id' => '8'),
            array('id' => '63','name' => 'Jamalpur','division_id' => '8'),
            array('id' => '64','name' => 'Netrokona','division_id' => '8')
          );


          foreach($districts as $district){
            \App\District::create($district);
        }

        $upazillas = array(
            array('id' => '1','name' => 'Debidwar','district_id' => '1'),
            array('id' => '2','name' => 'Barura','district_id' => '1'),
            array('id' => '3','name' => 'Brahmanpara','district_id' => '1'),
            array('id' => '4','name' => 'Chandina','district_id' => '1'),
            array('id' => '5','name' => 'Chauddagram','district_id' => '1'),
            array('id' => '6','name' => 'Daudkandi','district_id' => '1'),
            array('id' => '7','name' => 'Homna','district_id' => '1'),
            array('id' => '8','name' => 'Laksam','district_id' => '1'),
            array('id' => '9','name' => 'Muradnagar','district_id' => '1'),
            array('id' => '10','name' => 'Nangalkot','district_id' => '1'),
            array('id' => '11','name' => 'Comilla Sadar','district_id' => '1'),
            array('id' => '12','name' => 'Meghna','district_id' => '1'),
            array('id' => '13','name' => 'Monohargonj','district_id' => '1'),
            array('id' => '14','name' => 'Sadarsouth','district_id' => '1'),
            array('id' => '15','name' => 'Titas','district_id' => '1'),
            array('id' => '16','name' => 'Burichang','district_id' => '1'),
            array('id' => '17','name' => 'Lalmai','district_id' => '1'),
            array('id' => '18','name' => 'Chhagalnaiya','district_id' => '2'),
            array('id' => '19','name' => 'Feni Sadar','district_id' => '2'),
            array('id' => '20','name' => 'Sonagazi','district_id' => '2'),
            array('id' => '21','name' => 'Fulgazi','district_id' => '2'),
            array('id' => '22','name' => 'Parshuram','district_id' => '2'),
            array('id' => '23','name' => 'Daganbhuiyan','district_id' => '2'),
            array('id' => '24','name' => 'Brahmanbaria Sadar','district_id' => '3'),
            array('id' => '25','name' => 'Kasba','district_id' => '3'),
            array('id' => '26','name' => 'Nasirnagar','district_id' => '3'),
            array('id' => '27','name' => 'Sarail','district_id' => '3'),
            array('id' => '28','name' => 'Ashuganj','district_id' => '3'),
            array('id' => '29','name' => 'Akhaura','district_id' => '3'),
            array('id' => '30','name' => 'Nabinagar','district_id' => '3'),
            array('id' => '31','name' => 'Bancharampur','district_id' => '3'),
            array('id' => '32','name' => 'Bijoynagar','district_id' => '3'),
            array('id' => '33','name' => 'Rangamati Sadar','district_id' => '4'),
            array('id' => '34','name' => 'Kaptai','district_id' => '4'),
            array('id' => '35','name' => 'Kawkhali','district_id' => '4'),
            array('id' => '36','name' => 'Baghaichari','district_id' => '4'),
            array('id' => '37','name' => 'Barkal','district_id' => '4'),
            array('id' => '38','name' => 'Langadu','district_id' => '4'),
            array('id' => '39','name' => 'Rajasthali','district_id' => '4'),
            array('id' => '40','name' => 'Belaichari','district_id' => '4'),
            array('id' => '41','name' => 'Juraichari','district_id' => '4'),
            array('id' => '42','name' => 'Naniarchar','district_id' => '4'),
            array('id' => '43','name' => 'Noakhali Sadar','district_id' => '5'),
            array('id' => '44','name' => 'Companiganj','district_id' => '5'),
            array('id' => '45','name' => 'Begumganj','district_id' => '5'),
            array('id' => '46','name' => 'Hatia','district_id' => '5'),
            array('id' => '47','name' => 'Subarnachar','district_id' => '5'),
            array('id' => '48','name' => 'Kabirhat','district_id' => '5'),
            array('id' => '49','name' => 'Senbug','district_id' => '5'),
            array('id' => '50','name' => 'Chatkhil','district_id' => '5'),
            array('id' => '51','name' => 'Sonaimori','district_id' => '5'),
            array('id' => '52','name' => 'Haimchar','district_id' => '6'),
            array('id' => '53','name' => 'Kachua','district_id' => '6'),
            array('id' => '54','name' => 'Shahrasti','district_id' => '6'),
            array('id' => '55','name' => 'Chandpur Sadar','district_id' => '6'),
            array('id' => '56','name' => 'Matlab South','district_id' => '6'),
            array('id' => '57','name' => 'Hajiganj','district_id' => '6'),
            array('id' => '58','name' => 'Matlab North','district_id' => '6'),
            array('id' => '59','name' => 'Faridgonj','district_id' => '6'),
            array('id' => '60','name' => 'Lakshmipur Sadar','district_id' => '7'),
            array('id' => '61','name' => 'Kamalnagar','district_id' => '7'),
            array('id' => '62','name' => 'Raipur','district_id' => '7'),
            array('id' => '63','name' => 'Ramgati','district_id' => '7'),
            array('id' => '64','name' => 'Ramganj','district_id' => '7'),
            array('id' => '65','name' => 'Rangunia','district_id' => '8'),
            array('id' => '66','name' => 'Sitakunda','district_id' => '8'),
            array('id' => '67','name' => 'Mirsharai','district_id' => '8'),
            array('id' => '68','name' => 'Patiya','district_id' => '8'),
            array('id' => '69','name' => 'Sandwip','district_id' => '8'),
            array('id' => '70','name' => 'Banshkhali','district_id' => '8'),
            array('id' => '71','name' => 'Boalkhali','district_id' => '8'),
            array('id' => '72','name' => 'Anwara','district_id' => '8'),
            array('id' => '73','name' => 'Chandanaish','district_id' => '8'),
            array('id' => '74','name' => 'Satkania','district_id' => '8'),
            array('id' => '75','name' => 'Lohagara','district_id' => '8'),
            array('id' => '76','name' => 'Hathazari','district_id' => '8'),
            array('id' => '77','name' => 'Fatikchhari','district_id' => '8'),
            array('id' => '78','name' => 'Raozan','district_id' => '8'),
            array('id' => '79','name' => 'Karnafuli','district_id' => '8'),
            array('id' => '80','name' => 'Coxsbazar Sadar','district_id' => '9'),
            array('id' => '81','name' => 'Chakaria','district_id' => '9'),
            array('id' => '82','name' => 'Kutubdia','district_id' => '9'),
            array('id' => '83','name' => 'Ukhiya','district_id' => '9'),
            array('id' => '84','name' => 'Moheshkhali','district_id' => '9'),
            array('id' => '85','name' => 'Pekua','district_id' => '9'),
            array('id' => '86','name' => 'Ramu','district_id' => '9'),
            array('id' => '87','name' => 'Teknaf','district_id' => '9'),
            array('id' => '88','name' => 'Khagrachhari Sadar','district_id' => '10'),
            array('id' => '89','name' => 'Dighinala','district_id' => '10'),
            array('id' => '90','name' => 'Panchari','district_id' => '10'),
            array('id' => '91','name' => 'Laxmichhari','district_id' => '10'),
            array('id' => '92','name' => 'Mohalchari','district_id' => '10'),
            array('id' => '93','name' => 'Manikchari','district_id' => '10'),
            array('id' => '94','name' => 'Ramgarh','district_id' => '10'),
            array('id' => '95','name' => 'Matiranga','district_id' => '10'),
            array('id' => '96','name' => 'Guimara','district_id' => '10'),
            array('id' => '97','name' => 'Bandarban Sadar','district_id' => '11'),
            array('id' => '98','name' => 'Alikadam','district_id' => '11'),
            array('id' => '99','name' => 'Naikhongchhari','district_id' => '11'),
            array('id' => '100','name' => 'Rowangchhari','district_id' => '11'),
            array('id' => '101','name' => 'Lama','district_id' => '11'),
            array('id' => '102','name' => 'Ruma','district_id' => '11'),
            array('id' => '103','name' => 'Thanchi','district_id' => '11'),
            array('id' => '104','name' => 'Belkuchi','district_id' => '12'),
            array('id' => '105','name' => 'Chauhali','district_id' => '12'),
            array('id' => '106','name' => 'Kamarkhand','district_id' => '12'),
            array('id' => '107','name' => 'Kazipur','district_id' => '12'),
            array('id' => '108','name' => 'Raigonj','district_id' => '12'),
            array('id' => '109','name' => 'Shahjadpur','district_id' => '12'),
            array('id' => '110','name' => 'Sirajganj Sadar','district_id' => '12'),
            array('id' => '111','name' => 'Tarash','district_id' => '12'),
            array('id' => '112','name' => 'Ullapara','district_id' => '12'),
            array('id' => '113','name' => 'Sujanagar','district_id' => '13'),
            array('id' => '114','name' => 'Ishurdi','district_id' => '13'),
            array('id' => '115','name' => 'Bhangura','district_id' => '13'),
            array('id' => '116','name' => 'Pabna Sadar','district_id' => '13'),
            array('id' => '117','name' => 'Bera','district_id' => '13'),
            array('id' => '118','name' => 'Atghoria','district_id' => '13'),
            array('id' => '119','name' => 'Chatmohar','district_id' => '13'),
            array('id' => '120','name' => 'Santhia','district_id' => '13'),
            array('id' => '121','name' => 'Faridpur','district_id' => '13'),
            array('id' => '122','name' => 'Kahaloo','district_id' => '14'),
            array('id' => '123','name' => 'Bogra Sadar','district_id' => '14'),
            array('id' => '124','name' => 'Shariakandi','district_id' => '14'),
            array('id' => '125','name' => 'Shajahanpur','district_id' => '14'),
            array('id' => '126','name' => 'Dupchanchia','district_id' => '14'),
            array('id' => '127','name' => 'Adamdighi','district_id' => '14'),
            array('id' => '128','name' => 'Nondigram','district_id' => '14'),
            array('id' => '129','name' => 'Sonatala','district_id' => '14'),
            array('id' => '130','name' => 'Dhunot','district_id' => '14'),
            array('id' => '131','name' => 'Gabtali','district_id' => '14'),
            array('id' => '132','name' => 'Sherpur','district_id' => '14'),
            array('id' => '133','name' => 'Shibganj','district_id' => '14'),
            array('id' => '134','name' => 'Paba','district_id' => '15'),
            array('id' => '135','name' => 'Durgapur','district_id' => '15'),
            array('id' => '136','name' => 'Mohonpur','district_id' => '15'),
            array('id' => '137','name' => 'Charghat','district_id' => '15'),
            array('id' => '138','name' => 'Puthia','district_id' => '15'),
            array('id' => '139','name' => 'Bagha','district_id' => '15'),
            array('id' => '140','name' => 'Godagari','district_id' => '15'),
            array('id' => '141','name' => 'Tanore','district_id' => '15'),
            array('id' => '142','name' => 'Bagmara','district_id' => '15'),
            array('id' => '143','name' => 'Natore Sadar','district_id' => '16'),
            array('id' => '144','name' => 'Singra','district_id' => '16'),
            array('id' => '145','name' => 'Baraigram','district_id' => '16'),
            array('id' => '146','name' => 'Bagatipara','district_id' => '16'),
            array('id' => '147','name' => 'Lalpur','district_id' => '16'),
            array('id' => '148','name' => 'Gurudaspur','district_id' => '16'),
            array('id' => '149','name' => 'Naldanga','district_id' => '16'),
            array('id' => '150','name' => 'Akkelpur','district_id' => '17'),
            array('id' => '151','name' => 'Kalai','district_id' => '17'),
            array('id' => '152','name' => 'Khetlal','district_id' => '17'),
            array('id' => '153','name' => 'Panchbibi','district_id' => '17'),
            array('id' => '154','name' => 'Joypurhat Sadar','district_id' => '17'),
            array('id' => '155','name' => 'Chapainawabganj Sadar','district_id' => '18'),
            array('id' => '156','name' => 'Gomostapur','district_id' => '18'),
            array('id' => '157','name' => 'Nachol','district_id' => '18'),
            array('id' => '158','name' => 'Bholahat','district_id' => '18'),
            array('id' => '159','name' => 'Shibganj','district_id' => '18'),
            array('id' => '160','name' => 'Mohadevpur','district_id' => '19'),
            array('id' => '161','name' => 'Badalgachi','district_id' => '19'),
            array('id' => '162','name' => 'Patnitala','district_id' => '19'),
            array('id' => '163','name' => 'Dhamoirhat','district_id' => '19'),
            array('id' => '164','name' => 'Niamatpur','district_id' => '19'),
            array('id' => '165','name' => 'Manda','district_id' => '19'),
            array('id' => '166','name' => 'Atrai','district_id' => '19'),
            array('id' => '167','name' => 'Raninagar','district_id' => '19'),
            array('id' => '168','name' => 'Naogaon Sadar','district_id' => '19'),
            array('id' => '169','name' => 'Porsha','district_id' => '19'),
            array('id' => '170','name' => 'Sapahar','district_id' => '19'),
            array('id' => '171','name' => 'Manirampur','district_id' => '20'),
            array('id' => '172','name' => 'Abhaynagar','district_id' => '20'),
            array('id' => '173','name' => 'Bagherpara','district_id' => '20'),
            array('id' => '174','name' => 'Chougachha','district_id' => '20'),
            array('id' => '175','name' => 'Jhikargacha','district_id' => '20'),
            array('id' => '176','name' => 'Keshabpur','district_id' => '20'),
            array('id' => '177','name' => 'Jessore Sadar','district_id' => '20'),
            array('id' => '178','name' => 'Sharsha','district_id' => '20'),
            array('id' => '179','name' => 'Assasuni','district_id' => '21'),
            array('id' => '180','name' => 'Debhata','district_id' => '21'),
            array('id' => '181','name' => 'Kalaroa','district_id' => '21'),
            array('id' => '182','name' => 'Satkhira Sadar','district_id' => '21'),
            array('id' => '183','name' => 'Shyamnagar','district_id' => '21'),
            array('id' => '184','name' => 'Tala','district_id' => '21'),
            array('id' => '185','name' => 'Kaliganj','district_id' => '21'),
            array('id' => '186','name' => 'Mujibnagar','district_id' => '22'),
            array('id' => '187','name' => 'Meherpur Sadar','district_id' => '22'),
            array('id' => '188','name' => 'Gangni','district_id' => '22'),
            array('id' => '189','name' => 'Narail Sadar','district_id' => '23'),
            array('id' => '190','name' => 'Lohagara','district_id' => '23'),
            array('id' => '191','name' => 'Kalia','district_id' => '23'),
            array('id' => '192','name' => 'Chuadanga Sadar','district_id' => '24'),
            array('id' => '193','name' => 'Alamdanga','district_id' => '24'),
            array('id' => '194','name' => 'Damurhuda','district_id' => '24'),
            array('id' => '195','name' => 'Jibannagar','district_id' => '24'),
            array('id' => '196','name' => 'Kushtia Sadar','district_id' => '25'),
            array('id' => '197','name' => 'Kumarkhali','district_id' => '25'),
            array('id' => '198','name' => 'Khoksa','district_id' => '25'),
            array('id' => '199','name' => 'Mirpur','district_id' => '25'),
            array('id' => '200','name' => 'Daulatpur','district_id' => '25'),
            array('id' => '201','name' => 'Bheramara','district_id' => '25'),
            array('id' => '202','name' => 'Shalikha','district_id' => '26'),
            array('id' => '203','name' => 'Sreepur','district_id' => '26'),
            array('id' => '204','name' => 'Magura Sadar','district_id' => '26'),
            array('id' => '205','name' => 'Mohammadpur','district_id' => '26'),
            array('id' => '206','name' => 'Paikgasa','district_id' => '27'),
            array('id' => '207','name' => 'Fultola','district_id' => '27'),
            array('id' => '208','name' => 'Digholia','district_id' => '27'),
            array('id' => '209','name' => 'Rupsha','district_id' => '27'),
            array('id' => '210','name' => 'Terokhada','district_id' => '27'),
            array('id' => '211','name' => 'Dumuria','district_id' => '27'),
            array('id' => '212','name' => 'Botiaghata','district_id' => '27'),
            array('id' => '213','name' => 'Dakop','district_id' => '27'),
            array('id' => '214','name' => 'Koyra','district_id' => '27'),
            array('id' => '215','name' => 'Fakirhat','district_id' => '28'),
            array('id' => '216','name' => 'Bagerhat Sadar','district_id' => '28'),
            array('id' => '217','name' => 'Mollahat','district_id' => '28'),
            array('id' => '218','name' => 'Sarankhola','district_id' => '28'),
            array('id' => '219','name' => 'Rampal','district_id' => '28'),
            array('id' => '220','name' => 'Morrelganj','district_id' => '28'),
            array('id' => '221','name' => 'Kachua','district_id' => '28'),
            array('id' => '222','name' => 'Mongla','district_id' => '28'),
            array('id' => '223','name' => 'Chitalmari','district_id' => '28'),
            array('id' => '224','name' => 'Jhenaidah Sadar','district_id' => '29'),
            array('id' => '225','name' => 'Shailkupa','district_id' => '29'),
            array('id' => '226','name' => 'Harinakundu','district_id' => '29'),
            array('id' => '227','name' => 'Kaliganj','district_id' => '29'),
            array('id' => '228','name' => 'Kotchandpur','district_id' => '29'),
            array('id' => '229','name' => 'Moheshpur','district_id' => '29'),
            array('id' => '230','name' => 'Jhalakathi Sadar','district_id' => '30'),
            array('id' => '231','name' => 'Kathalia','district_id' => '30'),
            array('id' => '232','name' => 'Nalchity','district_id' => '30'),
            array('id' => '233','name' => 'Rajapur','district_id' => '30'),
            array('id' => '234','name' => 'Bauphal','district_id' => '31'),
            array('id' => '235','name' => 'Patuakhali Sadar','district_id' => '31'),
            array('id' => '236','name' => 'Dumki','district_id' => '31'),
            array('id' => '237','name' => 'Dashmina','district_id' => '31'),
            array('id' => '238','name' => 'Kalapara','district_id' => '31'),
            array('id' => '239','name' => 'Mirzaganj','district_id' => '31'),
            array('id' => '240','name' => 'Galachipa','district_id' => '31'),
            array('id' => '241','name' => 'Rangabali','district_id' => '31'),
            array('id' => '242','name' => 'Pirojpur Sadar','district_id' => '32'),
            array('id' => '243','name' => 'Nazirpur','district_id' => '32'),
            array('id' => '244','name' => 'Kawkhali','district_id' => '32'),
            array('id' => '245','name' => 'Zianagar','district_id' => '32'),
            array('id' => '246','name' => 'Bhandaria','district_id' => '32'),
            array('id' => '247','name' => 'Mathbaria','district_id' => '32'),
            array('id' => '248','name' => 'Nesarabad','district_id' => '32'),
            array('id' => '249','name' => 'Barisal Sadar','district_id' => '33'),
            array('id' => '250','name' => 'Bakerganj','district_id' => '33'),
            array('id' => '251','name' => 'Babuganj','district_id' => '33'),
            array('id' => '252','name' => 'Wazirpur','district_id' => '33'),
            array('id' => '253','name' => 'Banaripara','district_id' => '33'),
            array('id' => '254','name' => 'Gournadi','district_id' => '33'),
            array('id' => '255','name' => 'Agailjhara','district_id' => '33'),
            array('id' => '256','name' => 'Mehendiganj','district_id' => '33'),
            array('id' => '257','name' => 'Muladi','district_id' => '33'),
            array('id' => '258','name' => 'Hizla','district_id' => '33'),
            array('id' => '259','name' => 'Bhola Sadar','district_id' => '34'),
            array('id' => '260','name' => 'Borhan Sddin','district_id' => '34'),
            array('id' => '261','name' => 'Charfesson','district_id' => '34'),
            array('id' => '262','name' => 'Doulatkhan','district_id' => '34'),
            array('id' => '263','name' => 'Monpura','district_id' => '34'),
            array('id' => '264','name' => 'Tazumuddin','district_id' => '34'),
            array('id' => '265','name' => 'Lalmohan','district_id' => '34'),
            array('id' => '266','name' => 'Amtali','district_id' => '35'),
            array('id' => '267','name' => 'Barguna Sadar','district_id' => '35'),
            array('id' => '268','name' => 'Betagi','district_id' => '35'),
            array('id' => '269','name' => 'Bamna','district_id' => '35'),
            array('id' => '270','name' => 'Pathorghata','district_id' => '35'),
            array('id' => '271','name' => 'Taltali','district_id' => '35'),
            array('id' => '272','name' => 'Balaganj','district_id' => '36'),
            array('id' => '273','name' => 'Beanibazar','district_id' => '36'),
            array('id' => '274','name' => 'Bishwanath','district_id' => '36'),
            array('id' => '275','name' => 'Companiganj','district_id' => '36'),
            array('id' => '276','name' => 'Fenchuganj','district_id' => '36'),
            array('id' => '277','name' => 'Golapganj','district_id' => '36'),
            array('id' => '278','name' => 'Gowainghat','district_id' => '36'),
            array('id' => '279','name' => 'Jaintiapur','district_id' => '36'),
            array('id' => '280','name' => 'Kanaighat','district_id' => '36'),
            array('id' => '281','name' => 'Sylhet Sadar','district_id' => '36'),
            array('id' => '282','name' => 'Zakiganj','district_id' => '36'),
            array('id' => '283','name' => 'Dakshinsurma','district_id' => '36'),
            array('id' => '284','name' => 'Osmaninagar','district_id' => '36'),
            array('id' => '285','name' => 'Barlekha','district_id' => '37'),
            array('id' => '286','name' => 'Kamolganj','district_id' => '37'),
            array('id' => '287','name' => 'Kulaura','district_id' => '37'),
            array('id' => '288','name' => 'Moulvibazar Sadar','district_id' => '37'),
            array('id' => '289','name' => 'Rajnagar','district_id' => '37'),
            array('id' => '290','name' => 'Sreemangal','district_id' => '37'),
            array('id' => '291','name' => 'Juri','district_id' => '37'),
            array('id' => '292','name' => 'Nabiganj','district_id' => '38'),
            array('id' => '293','name' => 'Bahubal','district_id' => '38'),
            array('id' => '294','name' => 'Ajmiriganj','district_id' => '38'),
            array('id' => '295','name' => 'Baniachong','district_id' => '38'),
            array('id' => '296','name' => 'Lakhai','district_id' => '38'),
            array('id' => '297','name' => 'Chunarughat','district_id' => '38'),
            array('id' => '298','name' => 'Habiganj Sadar','district_id' => '38'),
            array('id' => '299','name' => 'Madhabpur','district_id' => '38'),
            array('id' => '300','name' => 'Sunamganj Sadar','district_id' => '39'),
            array('id' => '301','name' => 'South Sunamganj','district_id' => '39'),
            array('id' => '302','name' => 'Bishwambarpur','district_id' => '39'),
            array('id' => '303','name' => 'Chhatak','district_id' => '39'),
            array('id' => '304','name' => 'Jagannathpur','district_id' => '39'),
            array('id' => '305','name' => 'Dowarabazar','district_id' => '39'),
            array('id' => '306','name' => 'Tahirpur','district_id' => '39'),
            array('id' => '307','name' => 'Dharmapasha','district_id' => '39'),
            array('id' => '308','name' => 'Jamalganj','district_id' => '39'),
            array('id' => '309','name' => 'Shalla','district_id' => '39'),
            array('id' => '310','name' => 'Derai','district_id' => '39'),
            array('id' => '311','name' => 'Belabo','district_id' => '40'),
            array('id' => '312','name' => 'Monohardi','district_id' => '40'),
            array('id' => '313','name' => 'Narsingdi Sadar','district_id' => '40'),
            array('id' => '314','name' => 'Palash','district_id' => '40'),
            array('id' => '315','name' => 'Raipura','district_id' => '40'),
            array('id' => '316','name' => 'Shibpur','district_id' => '40'),
            array('id' => '317','name' => 'Kaliganj','district_id' => '41'),
            array('id' => '318','name' => 'Kaliakair','district_id' => '41'),
            array('id' => '319','name' => 'Kapasia','district_id' => '41'),
            array('id' => '320','name' => 'Gazipur Sadar','district_id' => '41'),
            array('id' => '321','name' => 'Sreepur','district_id' => '41'),
            array('id' => '322','name' => 'Shariatpur Sadar','district_id' => '42'),
            array('id' => '323','name' => 'Naria','district_id' => '42'),
            array('id' => '324','name' => 'Zajira','district_id' => '42'),
            array('id' => '325','name' => 'Gosairhat','district_id' => '42'),
            array('id' => '326','name' => 'Bhedarganj','district_id' => '42'),
            array('id' => '327','name' => 'Damudya','district_id' => '42'),
            array('id' => '328','name' => 'Araihazar','district_id' => '43'),
            array('id' => '329','name' => 'Bandar','district_id' => '43'),
            array('id' => '330','name' => 'Narayanganj Sadar','district_id' => '43'),
            array('id' => '331','name' => 'Rupganj','district_id' => '43'),
            array('id' => '332','name' => 'Sonargaon','district_id' => '43'),
            array('id' => '333','name' => 'Basail','district_id' => '44'),
            array('id' => '334','name' => 'Bhuapur','district_id' => '44'),
            array('id' => '335','name' => 'Delduar','district_id' => '44'),
            array('id' => '336','name' => 'Ghatail','district_id' => '44'),
            array('id' => '337','name' => 'Gopalpur','district_id' => '44'),
            array('id' => '338','name' => 'Madhupur','district_id' => '44'),
            array('id' => '339','name' => 'Mirzapur','district_id' => '44'),
            array('id' => '340','name' => 'Nagarpur','district_id' => '44'),
            array('id' => '341','name' => 'Sakhipur','district_id' => '44'),
            array('id' => '342','name' => 'Tangail Sadar','district_id' => '44'),
            array('id' => '343','name' => 'Kalihati','district_id' => '44'),
            array('id' => '344','name' => 'Dhanbari','district_id' => '44'),
            array('id' => '345','name' => 'Itna','district_id' => '45'),
            array('id' => '346','name' => 'Katiadi','district_id' => '45'),
            array('id' => '347','name' => 'Bhairab','district_id' => '45'),
            array('id' => '348','name' => 'Tarail','district_id' => '45'),
            array('id' => '349','name' => 'Hossainpur','district_id' => '45'),
            array('id' => '350','name' => 'Pakundia','district_id' => '45'),
            array('id' => '351','name' => 'Kuliarchar','district_id' => '45'),
            array('id' => '352','name' => 'Kishoreganj Sadar','district_id' => '45'),
            array('id' => '353','name' => 'Karimgonj','district_id' => '45'),
            array('id' => '354','name' => 'Bajitpur','district_id' => '45'),
            array('id' => '355','name' => 'Austagram','district_id' => '45'),
            array('id' => '356','name' => 'Mithamoin','district_id' => '45'),
            array('id' => '357','name' => 'Nikli','district_id' => '45'),
            array('id' => '358','name' => 'Harirampur','district_id' => '46'),
            array('id' => '359','name' => 'Saturia','district_id' => '46'),
            array('id' => '360','name' => 'Manikganj Sadar','district_id' => '46'),
            array('id' => '361','name' => 'Gior','district_id' => '46'),
            array('id' => '362','name' => 'Shibaloy','district_id' => '46'),
            array('id' => '363','name' => 'Doulatpur','district_id' => '46'),
            array('id' => '364','name' => 'Singiar','district_id' => '46'),
            array('id' => '365','name' => 'Savar','district_id' => '47'),
            array('id' => '366','name' => 'Dhamrai','district_id' => '47'),
            array('id' => '367','name' => 'Keraniganj','district_id' => '47'),
            array('id' => '368','name' => 'Nawabganj','district_id' => '47'),
            array('id' => '369','name' => 'Dohar','district_id' => '47'),
            array('id' => '370','name' => 'Munshiganj Sadar','district_id' => '48'),
            array('id' => '371','name' => 'Sreenagar','district_id' => '48'),
            array('id' => '372','name' => 'Sirajdikhan','district_id' => '48'),
            array('id' => '373','name' => 'Louhajanj','district_id' => '48'),
            array('id' => '374','name' => 'Gajaria','district_id' => '48'),
            array('id' => '375','name' => 'Tongibari','district_id' => '48'),
            array('id' => '376','name' => 'Rajbari Sadar','district_id' => '49'),
            array('id' => '377','name' => 'Goalanda','district_id' => '49'),
            array('id' => '378','name' => 'Pangsa','district_id' => '49'),
            array('id' => '379','name' => 'Baliakandi','district_id' => '49'),
            array('id' => '380','name' => 'Kalukhali','district_id' => '49'),
            array('id' => '381','name' => 'Madaripur Sadar','district_id' => '50'),
            array('id' => '382','name' => 'Shibchar','district_id' => '50'),
            array('id' => '383','name' => 'Kalkini','district_id' => '50'),
            array('id' => '384','name' => 'Rajoir','district_id' => '50'),
            array('id' => '385','name' => 'Gopalganj Sadar','district_id' => '51'),
            array('id' => '386','name' => 'Kashiani','district_id' => '51'),
            array('id' => '387','name' => 'Tungipara','district_id' => '51'),
            array('id' => '388','name' => 'Kotalipara','district_id' => '51'),
            array('id' => '389','name' => 'Muksudpur','district_id' => '51'),
            array('id' => '390','name' => 'Faridpur Sadar','district_id' => '52'),
            array('id' => '391','name' => 'Alfadanga','district_id' => '52'),
            array('id' => '392','name' => 'Boalmari','district_id' => '52'),
            array('id' => '393','name' => 'Sadarpur','district_id' => '52'),
            array('id' => '394','name' => 'Nagarkanda','district_id' => '52'),
            array('id' => '395','name' => 'Bhanga','district_id' => '52'),
            array('id' => '396','name' => 'Charbhadrasan','district_id' => '52'),
            array('id' => '397','name' => 'Madhukhali','district_id' => '52'),
            array('id' => '398','name' => 'Saltha','district_id' => '52'),
            array('id' => '399','name' => 'Panchagarh Sadar','district_id' => '53'),
            array('id' => '400','name' => 'Debiganj','district_id' => '53'),
            array('id' => '401','name' => 'Boda','district_id' => '53'),
            array('id' => '402','name' => 'Atwari','district_id' => '53'),
            array('id' => '403','name' => 'Tetulia','district_id' => '53'),
            array('id' => '404','name' => 'Nawabganj','district_id' => '54'),
            array('id' => '405','name' => 'Birganj','district_id' => '54'),
            array('id' => '406','name' => 'Ghoraghat','district_id' => '54'),
            array('id' => '407','name' => 'Birampur','district_id' => '54'),
            array('id' => '408','name' => 'Parbatipur','district_id' => '54'),
            array('id' => '409','name' => 'Bochaganj','district_id' => '54'),
            array('id' => '410','name' => 'Kaharol','district_id' => '54'),
            array('id' => '411','name' => 'Fulbari','district_id' => '54'),
            array('id' => '412','name' => 'Dinajpur Sadar','district_id' => '54'),
            array('id' => '413','name' => 'Hakimpur','district_id' => '54'),
            array('id' => '414','name' => 'Khansama','district_id' => '54'),
            array('id' => '415','name' => 'Birol','district_id' => '54'),
            array('id' => '416','name' => 'Chirirbandar','district_id' => '54'),
            array('id' => '417','name' => 'Lalmonirhat Sadar','district_id' => '55'),
            array('id' => '418','name' => 'Kaliganj','district_id' => '55'),
            array('id' => '419','name' => 'Hatibandha','district_id' => '55'),
            array('id' => '420','name' => 'Patgram','district_id' => '55'),
            array('id' => '421','name' => 'Aditmari','district_id' => '55'),
            array('id' => '422','name' => 'Syedpur','district_id' => '56'),
            array('id' => '423','name' => 'Domar','district_id' => '56'),
            array('id' => '424','name' => 'Dimla','district_id' => '56'),
            array('id' => '425','name' => 'Jaldhaka','district_id' => '56'),
            array('id' => '426','name' => 'Kishorganj','district_id' => '56'),
            array('id' => '427','name' => 'Nilphamari Sadar','district_id' => '56'),
            array('id' => '428','name' => 'Sadullapur','district_id' => '57'),
            array('id' => '429','name' => 'Gaibandha Sadar','district_id' => '57'),
            array('id' => '430','name' => 'Palashbari','district_id' => '57'),
            array('id' => '431','name' => 'Saghata','district_id' => '57'),
            array('id' => '432','name' => 'Gobindaganj','district_id' => '57'),
            array('id' => '433','name' => 'Sundarganj','district_id' => '57'),
            array('id' => '434','name' => 'Phulchari','district_id' => '57'),
            array('id' => '435','name' => 'Thakurgaon Sadar','district_id' => '58'),
            array('id' => '436','name' => 'Pirganj','district_id' => '58'),
            array('id' => '437','name' => 'Ranisankail','district_id' => '58'),
            array('id' => '438','name' => 'Haripur','district_id' => '58'),
            array('id' => '439','name' => 'Baliadangi','district_id' => '58'),
            array('id' => '440','name' => 'Rangpur Sadar','district_id' => '59'),
            array('id' => '441','name' => 'Gangachara','district_id' => '59'),
            array('id' => '442','name' => 'Taragonj','district_id' => '59'),
            array('id' => '443','name' => 'Badargonj','district_id' => '59'),
            array('id' => '444','name' => 'Mithapukur','district_id' => '59'),
            array('id' => '445','name' => 'Pirgonj','district_id' => '59'),
            array('id' => '446','name' => 'Kaunia','district_id' => '59'),
            array('id' => '447','name' => 'Pirgacha','district_id' => '59'),
            array('id' => '448','name' => 'Kurigram Sadar','district_id' => '60'),
            array('id' => '449','name' => 'Nageshwari','district_id' => '60'),
            array('id' => '450','name' => 'Bhurungamari','district_id' => '60'),
            array('id' => '451','name' => 'Phulbari','district_id' => '60'),
            array('id' => '452','name' => 'Rajarhat','district_id' => '60'),
            array('id' => '453','name' => 'Ulipur','district_id' => '60'),
            array('id' => '454','name' => 'Chilmari','district_id' => '60'),
            array('id' => '455','name' => 'Rowmari','district_id' => '60'),
            array('id' => '456','name' => 'Charrajibpur','district_id' => '60'),
            array('id' => '457','name' => 'Sherpur Sadar','district_id' => '61'),
            array('id' => '458','name' => 'Nalitabari','district_id' => '61'),
            array('id' => '459','name' => 'Sreebordi','district_id' => '61'),
            array('id' => '460','name' => 'Nokla','district_id' => '61'),
            array('id' => '461','name' => 'Jhenaigati','district_id' => '61'),
            array('id' => '462','name' => 'Fulbaria','district_id' => '62'),
            array('id' => '463','name' => 'Trishal','district_id' => '62'),
            array('id' => '464','name' => 'Bhaluka','district_id' => '62'),
            array('id' => '465','name' => 'Muktagacha','district_id' => '62'),
            array('id' => '466','name' => 'Mymensingh Sadar','district_id' => '62'),
            array('id' => '467','name' => 'Dhobaura','district_id' => '62'),
            array('id' => '468','name' => 'Phulpur','district_id' => '62'),
            array('id' => '469','name' => 'Haluaghat','district_id' => '62'),
            array('id' => '470','name' => 'Gouripur','district_id' => '62'),
            array('id' => '471','name' => 'Gafargaon','district_id' => '62'),
            array('id' => '472','name' => 'Iswarganj','district_id' => '62'),
            array('id' => '473','name' => 'Nandail','district_id' => '62'),
            array('id' => '474','name' => 'Tarakanda','district_id' => '62'),
            array('id' => '475','name' => 'Jamalpur Sadar','district_id' => '63'),
            array('id' => '476','name' => 'Melandah','district_id' => '63'),
            array('id' => '477','name' => 'Islampur','district_id' => '63'),
            array('id' => '478','name' => 'Dewangonj','district_id' => '63'),
            array('id' => '479','name' => 'Sarishabari','district_id' => '63'),
            array('id' => '480','name' => 'Madarganj','district_id' => '63'),
            array('id' => '481','name' => 'Bokshiganj','district_id' => '63'),
            array('id' => '482','name' => 'Barhatta','district_id' => '64'),
            array('id' => '483','name' => 'Durgapur','district_id' => '64'),
            array('id' => '484','name' => 'Kendua','district_id' => '64'),
            array('id' => '485','name' => 'Atpara','district_id' => '64'),
            array('id' => '486','name' => 'Madan','district_id' => '64'),
            array('id' => '487','name' => 'Khaliajuri','district_id' => '64'),
            array('id' => '488','name' => 'Kalmakanda','district_id' => '64'),
            array('id' => '489','name' => 'Mohongonj','district_id' => '64'),
            array('id' => '490','name' => 'Purbadhala','district_id' => '64'),
            array('id' => '491','name' => 'Netrokona Sadar','district_id' => '64')
          );

          foreach($upazillas as $upazilla){
            \App\Upazilla::create($upazilla);
        }

    }
}
